// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yitbnvhmojmjqamuoakd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpdGJudmhtb2ptanFhbXVvYWtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NzgzMDMsImV4cCI6MjA3MDI1NDMwM30.nPDVCnjHwCCA98423mHlz3b1HuplD7o8NbdRtB5015I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});